name: nightly build at 11pm

on:
  schedule:
    - cron: "0 23 * * *"

jobs:
  nightly-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: run unit test
        run: mvn test

      - name: build with maven
        run: mvn -DskipTests -B package --no-transfer-progress --file ./pom.xml

      - uses: actions/upload-artifact@master
        with:
          name: sejutu.war
          path: ./target/*serenity-junit-starter*.war
